name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Prepare process.json for PM2
        run: /var/www/scripts/process.sh Covid-Tracker server/

      - name: Install npm packages
        run: |
          cd client
          npm install
          cd ../server
          npm install 

      - name: Build vue.js app
        run: |
          cd client
          npm run build

      - name: Upload dist file 
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: client/dist
  
  deploy: 
    needs: [build]
    env: 
      PROJECT_DIR: /var/www/covid-tracker
    runs-on: self-hosted 
    steps: 
      - name: Download dist file from build job
        uses: actions/download-artifact@v2
        with:
          name: dist

      - name: Copy files to /var/www
        run: |
          cp -r ./* $PROJECT_DIR
          cd $PROJECT_DIR/server
          pm2 start process.json
