name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Prepare process.json for PM2
        run: /var/www/scripts/process.sh Covid-Tracker server/

      - name: Install npm packages
        run: |
          cd client
          npm install
          cd ../server
          npm install 

      - name: Build vue.js app
        run: |
          cd client
          npm run build
  
  deploy: 
    needs: [build]
    env: 
      PROJECT_DIR: /var/www/covid-tracker
    runs-on: self-hosted 
    steps: 
      - name: Copy files to /var/www
        run: |
          rm -rf $PROJECT_DIR/client/dist
          shopt -s extglob
          cp -r !(client/node_modules) $PROJECT_DIR
          cd $PROJECT_DIR/server
          pm2 start process.json
