name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    env: 
      PORT_PROD: 8082
    steps:
      - uses: actions/checkout@v2

      - name: Prepare process.json for PM2
        run: |
          /var/www/scripts/env.sh master server/
          /var/www/scripts/process.sh Covid-Tracker server/

      - name: Install npm packages
        run: |
          cd client
          npm install
          cd ../server
          npm install 

      - name: Build vue.js app
        run: |
          cd client
          npm run build
  
  deploy: 
    runs-on: self-hosted 
    needs: [build]
    env: 
      PROJECT_DIR: /var/www/covid-tracker
    steps: 
      - name: Copy files to /var/www
        run: |
          rm -rf $PROJECT_DIR/client/dist
          rm -rf client/node_modules
          cp -r ./ $PROJECT_DIR
          cd $PROJECT_DIR/server
          pm2 start process.json
